/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for AstronautDuty controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, GetAstronautDutiesByNameResult, CreateAstronautDuty, CreateAstronautDutyResult } from "../models";

@Injectable({ providedIn: "root" })
export class AstronautDutyService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    astronautDutyNameGet(name: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<GetAstronautDutiesByNameResult>;
    astronautDutyNameGet(name: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetAstronautDutiesByNameResult>>;
    astronautDutyNameGet(name: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetAstronautDutiesByNameResult>>;
    astronautDutyNameGet(name: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/AstronautDuty/${name}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    astronautDutyPost(createAstronautDuty?: CreateAstronautDuty, observe?: 'body', options?: RequestOptions<'json'>): Observable<CreateAstronautDutyResult>;
    astronautDutyPost(createAstronautDuty?: CreateAstronautDuty, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CreateAstronautDutyResult>>;
    astronautDutyPost(createAstronautDuty?: CreateAstronautDuty, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CreateAstronautDutyResult>>;
    astronautDutyPost(createAstronautDuty?: CreateAstronautDuty, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/AstronautDuty`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createAstronautDuty, requestOptions);
    }
}
