/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Person controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, GetPeopleResult, CreatePerson, CreatePersonResult, UpdatePerson, UpdatePersonResult, GetPersonByNameResult } from "../models";

@Injectable({ providedIn: "root" })
export class PersonService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    personGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<GetPeopleResult>;
    personGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetPeopleResult>>;
    personGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetPeopleResult>>;
    personGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/Person`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    personPost(createPerson?: CreatePerson, observe?: 'body', options?: RequestOptions<'json'>): Observable<CreatePersonResult>;
    personPost(createPerson?: CreatePerson, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CreatePersonResult>>;
    personPost(createPerson?: CreatePerson, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CreatePersonResult>>;
    personPost(createPerson?: CreatePerson, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/Person`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createPerson, requestOptions);
    }

    personPut(updatePerson?: UpdatePerson, observe?: 'body', options?: RequestOptions<'json'>): Observable<UpdatePersonResult>;
    personPut(updatePerson?: UpdatePerson, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UpdatePersonResult>>;
    personPut(updatePerson?: UpdatePerson, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UpdatePersonResult>>;
    personPut(updatePerson?: UpdatePerson, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/Person`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, updatePerson, requestOptions);
    }

    personNameGet(name: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<GetPersonByNameResult>;
    personNameGet(name: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetPersonByNameResult>>;
    personNameGet(name: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetPersonByNameResult>>;
    personNameGet(name: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/Person/${name}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
