/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface AstronautDetail {
    id?: number;
    personId?: number;
    currentRank?: string | null;
    currentDutyTitle?: string | null;
    careerStartDate?: Date;
    careerEndDate?: Date | null;
    person?: Person;
}

export interface AstronautDuty {
    id?: number;
    personId?: number;
    rank?: string | null;
    dutyTitle?: string | null;
    dutyStartDate?: Date;
    dutyEndDate?: Date | null;
    person?: Person;
}

export interface CreateAstronautDuty {
    name?: string | null;
    rank?: string | null;
    dutyTitle?: string | null;
    dutyStartDate?: Date;
}

export interface CreateAstronautDutyResult {
    success?: boolean;
    message?: string | null;
    responseCode?: number;
    id?: number | null;
}

export interface CreatePerson {
    name?: string | null;
}

export interface CreatePersonResult {
    success?: boolean;
    message?: string | null;
    responseCode?: number;
    id?: number;
}

export interface GetAstronautDutiesByNameResult {
    success?: boolean;
    message?: string | null;
    responseCode?: number;
    person?: PersonAstronaut;
    astronautDuties?: Array<AstronautDuty>;
}

export interface GetPeopleResult {
    success?: boolean;
    message?: string | null;
    responseCode?: number;
    people?: Array<PersonAstronaut>;
}

export interface GetPersonByNameResult {
    success?: boolean;
    message?: string | null;
    responseCode?: number;
    person?: PersonAstronaut;
}

export interface Person {
    id?: number;
    name?: string | null;
    astronautDetail?: AstronautDetail;
    astronautDuties?: Array<AstronautDuty>;
}

export interface PersonAstronaut {
    personId?: number;
    name?: string | null;
    currentRank?: string | null;
    currentDutyTitle?: string | null;
    careerStartDate?: Date | null;
    careerEndDate?: Date | null;
}

export interface ProblemDetails {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
}

export interface UpdatePerson {
    name?: string | null;
    newName?: string | null;
}

export interface UpdatePersonResult {
    success?: boolean;
    message?: string | null;
    responseCode?: number;
    id?: number;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
